### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: GetOpenFileName failed with error 2

### ISSUE THREAD

**Issue by mfn** [steos/jnafilechooser#1]
Trying out the demos, this is what I get:

Running `NativePorcelainDemo` and clicking "Choose File" I get:

``` java
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: GetOpenFileName failed with error 2
    at jnafilechooser.api.WindowsFileChooser.showDialog(WindowsFileChooser.java:229)
    at jnafilechooser.api.WindowsFileChooser.showOpenDialog(WindowsFileChooser.java:143)
    at jnafilechooser.demo.NativePorcelainDemo$1.actionPerformed(NativePorcelainDemo.java:53)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
    at java.awt.Component.processMouseEvent(Component.java:6288)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
    at java.awt.Component.processEvent(Component.java:6053)
    at java.awt.Container.processEvent(Container.java:2041)
    at java.awt.Component.dispatchEventImpl(Component.java:4651)
    at java.awt.Container.dispatchEventImpl(Container.java:2099)
    at java.awt.Component.dispatchEvent(Component.java:4481)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4577)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4238)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
    at java.awt.Container.dispatchEventImpl(Container.java:2085)
    at java.awt.Window.dispatchEventImpl(Window.java:2478)
    at java.awt.Component.dispatchEvent(Component.java:4481)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:643)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$2.run(EventQueue.java:616)
    at java.awt.EventQueue$2.run(EventQueue.java:614)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:613)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

It's the same for the `PlumbingDemo` and "Choose file", however there the code shows only the error code: **2**

The `PortablePorcelainDemo` only throws the exception in this circumstance:
- Enable multiselect : unchecked
- Selection mode: Files

According to http://msdn.microsoft.com/en-us/library/ms646916%28v=vs.85%29.aspx the error means CDERR_INITIALIZATION , however I wouldn't know how not enough memory would be available.

Tested this on Windows 7 64bit Pro:

```
>java -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)
```

**Comment by steos** [comment]
Hi,

thank you for the report.

Unfortunately I can no longer reproduce this issue. I have updated to jna 3.3.0. If you still have the problem could you please test if it's fixed by this upgrade? 

thanks
Stefan

**Comment by mfn** [comment]
I missed the comment "back then", not using it anymore 🤷‍♀️
